In [1]:
import pandas

In [2]:
aisles = pandas.read_csv("E:/python大数据资料/黑马-02-最简单快速入门python机器学习/资料/机器学习day1资料/02-代码/instacart/aisles.csv")
order_products = pandas.read_csv("E:/python大数据资料/黑马-02-最简单快速入门python机器学习/资料/机器学习day1资料/02-代码/instacart/order_products__prior.csv")
orders = pandas.read_csv("E:/python大数据资料/黑马-02-最简单快速入门python机器学习/资料/机器学习day1资料/02-代码/instacart/orders.csv")
products = pandas.read_csv("E:/python大数据资料/黑马-02-最简单快速入门python机器学习/资料/机器学习day1资料/02-代码/instacart/products.csv")

In [3]:
# 2、合并表，将user_id和aisle_id合并到一起
# 2.1、将orders表和order_products__prior进行合并
order_order_product_data = pandas.merge(orders, order_products,on=["order_id", "order_id"])
# 2.2、将order_order_product_data表和products表进行合并
product_order_product_data = pandas.merge(order_order_product_data, products,on=["product_id", "product_id"])

In [4]:
product_order_product_data

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7
5,3367565,1,prior,6,2,7,19.0,196,1,1,Soda,77,7
6,550135,1,prior,7,1,9,20.0,196,1,1,Soda,77,7
7,3108588,1,prior,8,1,14,14.0,196,2,1,Soda,77,7
8,2295261,1,prior,9,1,16,0.0,196,4,1,Soda,77,7
9,2550362,1,prior,10,4,8,30.0,196,1,1,Soda,77,7
10,2968173,15,prior,15,1,9,7.0,196,2,0,Soda,77,7
11,1870022,15,prior,17,2,16,8.0,196,6,1,Soda,77,7
12,1911383,15,prior,18,2,11,7.0,196,1,1,Soda,77,7
13,2715276,15,prior,21,1,9,7.0,196,1,1,Soda,77,7
14,487368,15,prior,22,1,10,14.0,196,1,1,Soda,77,7
15,2293453,19,prior,2,5,14,6.0,196,3,0,Soda,77,7
16,1973799,19,prior,5,6,12,8.0,196,15,1,Soda,77,7
17,532817,19,prior,7,4,17,6.0,196,1,1,Soda,77,7
18,1573906,21,prior,10,3,10,6.0,196,2,0,Soda,77,7
19,1593000,31,prior,10,3,8,7.0,196,17,0,Soda,77,7
20,2231262,31,prior,17,3,11,8.0,196,14,1,Soda,77,7
21,2580647,43,prior,6,4,16,4.0,196,9,0,Soda,77,7
22,2187180,43,prior,9,4,12,3.0,196,1,1,Soda,77,7
23,2497897,52,prior,1,1,9,NaN,196,4,0,Soda,77,7
24,1318871,52,prior,2,1,10,7.0,196,5,1,Soda,77,7
25,1261384,52,prior,3,1,10,7.0,196,3,1,Soda,77,7
26,580568,52,prior,5,2,10,8.0,196,6,1,Soda,77,7
27,2428073,52,prior,7,2,7,8.0,196,5,1,Soda,77,7
28,342306,52,prior,9,1,11,7.0,196,5,1,Soda,77,7
29,1520353,52,prior,10,2,10,8.0,196,4,1,Soda,77,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434459,131322,193840,prior,3,0,14,12.0,19259,10,0,Florentine Spinach and Cheese Pasta Sauce,9,9
32434460,2990238,194078,prior,4,1,13,10.0,40747,29,0,Whitening Plus Scope Crest Complete Multi-Bene...,20,11
32434461,3294485,202763,prior,27,0,16,30.0,40747,13,0,Whitening Plus Scope Crest Complete Multi-Bene...,20,11
32434462,2706073,194639,prior,25,5,11,16.0,45378,10,0,Miss Treated Conditioner,22,11
32434463,346319,196040,prior,9,3,16,16.0,35952,13,0,Peachtree Schnapps,124,5
32434464,828012,196359,prior,2,1,7,8.0,48343,6,0,Hennepin Farmhouse Ale,27,5
32434465,2608655,197349,prior,1,3,15,NaN,9818,9,0,Cld/Flu Van Chrry,11,11
32434466,3004721,197459,prior,2,4,20,4.0,44495,1,0,Lowfat Cherry Lime Supernova Kefir Cultured Mi...,120,16
32434467,2216423,198107,prior,2,5,16,7.0,29713,4,0,18 Year Scotch Whisky,124,5
32434468,136517,198107,prior,4,1,13,8.0,29713,3,1,18 Year Scotch Whisky,124,5
32434469,461844,200351,prior,5,2,11,9.0,15408,2,0,Training Fluoride Free Toothpaste Apple & Ban...,20,11
32434470,216145,205587,prior,1,3,14,NaN,15408,6,0,Training Fluoride Free Toothpaste Apple & Ban...,20,11
32434471,2941852,200463,prior,2,1,15,30.0,8682,11,0,All Purpose Eraser,114,17
32434472,2321285,203389,prior,16,2,10,6.0,8682,7,0,All Purpose Eraser,114,17
32434473,609055,202557,prior,1,0,13,NaN,43553,2,0,Orange Energy Shots,64,7
32434474,1928449,202557,prior,4,4,9,16.0,43553,4,1,Orange Energy Shots,64,7
32434475,2222639,202557,prior,6,5,9,4.0,43553,3,1,Orange Energy Shots,64,7
32434476,339942,202557,prior,8,4,10,4.0,43553,3,1,Orange Energy Shots,64,7
32434477,2798193,202557,prior,9,4,13,7.0,43553,5,1,Orange Energy Shots,64,7
32434478,2391791,202557,prior,11,6,6,8.0,43553,2,1,Orange Energy Shots,64,7
32434479,576295,202557,prior,12,3,10,11.0,43553,14,1,Orange Energy Shots,64,7
32434480,960088,202557,prior,13,4,12,15.0,43553,3,1,Orange Energy Shots,64,7
32434481,343962,202557,prior,14,0,10,3.0,43553,2,1,Orange Energy Shots,64,7
32434482,2329472,202557,prior,15,6,12,6.0,43553,2,1,Orange Energy Shots,64,7
32434483,694731,202557,prior,16,1,14,2.0,43553,2,1,Orange Energy Shots,64,7
32434484,1320836,202557,prior,17,2,15,1.0,43553,2,1,Orange Energy Shots,64,7
32434485,31526,202557,prior,18,5,11,3.0,43553,2,1,Orange Energy Shots,64,7
32434486,758936,203436,prior,1,2,7,NaN,42338,4,0,"Zucchini Chips, Pesto",50,19
32434487,2745165,203436,prior,2,3,5,15.0,42338,16,1,"Zucchini Chips, Pesto",50,19
32434488,3093936,205420,prior,1,4,14,NaN,28818,8,0,Hot Oatmeal Multigrain Raisin,130,14

In [15]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [4]:
data = pandas.merge(product_order_product_data,aisles,on=["aisle_id","aisle_id"])
# product_order_product_data = pandas.merge(order_order_product_data, products,on=["product_id", "product_id"])

In [6]:
data.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,soft drinks
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,soft drinks
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,soft drinks
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,soft drinks
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,soft drinks

In [39]:
# 3、找到user_id和aisle_id的关系(将表转换成one-hot编码)
data1 = data[:1000000]
# table = pandas.crosstab(data1["user_id"],data1["aisle_id"])
table1 = pandas.crosstab(data1["user_id"], data1["aisle"])

In [40]:
table1

aisle    popcorn jerky  soft drinks  soy lactosefree
user_id
1                   10           13                2
2                    0            0                1
3                    0            0               15
4                    0            1                0
6                    0            0                1
7                    0            0               13
8                    0            0                2
9                    0            4                2
11                   0            6                3
12                   0            0                2
13                   0            0                3
15                  10            9                0
16                   0            0                3
17                   0           18                0
18                   0            0                4
19                   0            6                0
21                   0            6                1
23                   0            1                0
26                   0            0                1
27                   0           28               31
28                   0            8                4
29                   0            1                0
31                   0           27                4
35                   0            1               10
37                   0            0                3
38                   0            0               12
39                   0            0                1
41                   0            0                4
43                   0            3                1
44                   0            1                0
...                ...          ...              ...
206174               0            3                9
206175               0            0                1
206176               0            0                6
206177               0            0                4
206178               0            0                1
206180               0            0                2
206182               0            6                0
206183               0            4                9
206184               0            0                1
206185               0            1                0
206186               0            2                0
206187               0            0                2
206190               0            7                0
206191               0            0                3
206192               0            0                1
206193               0            0               13
206194               0            0                4
206195               0            2                0
206196               0            0                1
206197               0            1               10
206199               0           12                0
206200               0            1                8
206201               0           17                0
206202               0            1                9
206203               0            0                1
206204               0            0                2
206205               0            0                1
206206               0            8                1
206208               0            0               24
206209               0           10                9

[130520 rows x 3 columns]

In [23]:
from sklearn.decomposition import PCA

In [44]:
# 4、创建一个PCA转换器
transfer = PCA(n_components=0.95)

In [45]:
pcaData = transfer.fit_transform(table1)

In [46]:
pcaData.shape

(130520, 2)